/******************************************************************************
 ** File: Rte_SYS_KPI_ADAPTER_Type.h
 ** Role: The Application Types Header File provides a component local name space for enumeration literals and range values 
 ** Generated by Dassault Systèmes Rte Generator
 ** Date: 2023-02-09 08:57:05
 ** Template Version: 0.1
 **
 ** Controller / Compiler / Hardware independent
 **
 ** Copyright 2012 by Dassault Systèmes
 ** All rights exclusively reserved for Dassault Systèmes,
 ** unless expressly agreed to otherwise.
 ** Traceability: [rte_sws_7121][rte_sws_7122][rte_sws_7123][rte_sws_7124][rte_sws_2627]
*******************************************************************************/

/* Rte_SYS_KPI_ADAPTER_Type.h *************************************************/

/* Rte Generator V2 section ***************************************************/

/** Traceability [rte_sws_7678]*/
#ifndef RTE_SYS_KPI_ADAPTER_TYPE_H
#define RTE_SYS_KPI_ADAPTER_TYPE_H


/* Inclusions ================================================================*/
#include "Rte_Type.h"         /* RTE types header file Traceability [rte_sws_7127]*/
/** Traceability [rte_sws_7123] The declarations below are included only by the SwC, not by the RTE */

/* Implementation Data Type Symbols Traceability [rte_sws_6718]===============*/


/* Macros for accessing Availability Information in Structs for optional Members [SWS_Rte_3611][SWS_Rte_3612][SWS_Rte_3613][SWS_Rte_3614][SWS_Rte_3615][SWS_Rte_3616][SWS_Rte_3617][SWS_Rte_3618]===============*/


/* RTE Modes Traceability [rte_sws_2659][rte_sws_2627][rte_sws_2568]==========*/


/* Enumeration Data Types Traceability [rte_sws_3809][rte_sws_3810]===========*/
#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef e_KPI_EMPTY
#define e_KPI_EMPTY 0U
#endif /* e_KPI_EMPTY */

#ifndef e_KPI_SBL_COLD_START
#define e_KPI_SBL_COLD_START 1U
#endif /* e_KPI_SBL_COLD_START */

#ifndef e_KPI_SBL_WARM_START
#define e_KPI_SBL_WARM_START 2U
#endif /* e_KPI_SBL_WARM_START */

#ifndef e_KPI_SBL_END
#define e_KPI_SBL_END 3U
#endif /* e_KPI_SBL_END */

#ifndef e_KPI_UFBL_START
#define e_KPI_UFBL_START 4U
#endif /* e_KPI_UFBL_START */

#ifndef e_KPI_UFBL_END
#define e_KPI_UFBL_END 5U
#endif /* e_KPI_UFBL_END */

#ifndef e_KPI_APPL_START
#define e_KPI_APPL_START 6U
#endif /* e_KPI_APPL_START */

#ifndef e_KPI_APPL_START_COMMUNICATION_INIT
#define e_KPI_APPL_START_COMMUNICATION_INIT 7U
#endif /* e_KPI_APPL_START_COMMUNICATION_INIT */

#ifndef e_KPI_APPL_END_COMMUNICATION_INIT
#define e_KPI_APPL_END_COMMUNICATION_INIT 8U
#endif /* e_KPI_APPL_END_COMMUNICATION_INIT */

#ifndef e_KPI_APPL_NM_1ST_MESSAGE
#define e_KPI_APPL_NM_1ST_MESSAGE 9U
#endif /* e_KPI_APPL_NM_1ST_MESSAGE */

#ifndef e_KPI_APPL_START_MEMSTACK_INIT
#define e_KPI_APPL_START_MEMSTACK_INIT 10U
#endif /* e_KPI_APPL_START_MEMSTACK_INIT */

#ifndef e_KPI_APPL_END_MEMSTACK_INIT
#define e_KPI_APPL_END_MEMSTACK_INIT 11U
#endif /* e_KPI_APPL_END_MEMSTACK_INIT */

#ifndef e_KPI_TIME_BEFORE_RESET
#define e_KPI_TIME_BEFORE_RESET 12U
#endif /* e_KPI_TIME_BEFORE_RESET */

#ifndef e_KPI_APPL_END_ECUM_INIT
#define e_KPI_APPL_END_ECUM_INIT 13U
#endif /* e_KPI_APPL_END_ECUM_INIT */

#ifndef e_KPI_APPL_END_COMMUNICATION2_INIT
#define e_KPI_APPL_END_COMMUNICATION2_INIT 14U
#endif /* e_KPI_APPL_END_COMMUNICATION2_INIT */

#ifndef e_KPI_APPL_END_POSTLOAD
#define e_KPI_APPL_END_POSTLOAD 15U
#endif /* e_KPI_APPL_END_POSTLOAD */

#ifndef e_KPI_APPL_END_INIT
#define e_KPI_APPL_END_INIT 16U
#endif /* e_KPI_APPL_END_INIT */

#ifndef e_KPI_APPL_START_ECUM_INIT
#define e_KPI_APPL_START_ECUM_INIT 17U
#endif /* e_KPI_APPL_START_ECUM_INIT */

#ifndef e_KPI_APPL_TX_1ST_MESSAGE
#define e_KPI_APPL_TX_1ST_MESSAGE 18U
#endif /* e_KPI_APPL_TX_1ST_MESSAGE */

#ifndef e_KPI_RESERVED_7
#define e_KPI_RESERVED_7 19U
#endif /* e_KPI_RESERVED_7 */

#ifndef e_KPI_MAX_NUMBER
#define e_KPI_MAX_NUMBER 20U
#endif /* e_KPI_MAX_NUMBER */


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */


/* BitField Data Types Traceability [SWS_Rte_07410][SWS_Rte_07411][SWS_Rte_07412]===========*/
#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */


/* Range Data Types Traceability [rte_sws_5052][rte_sws_8402][rte_sws_5051][rte_sws_8403]*/
#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */


/* Activating Rte Event Data Types [SWS_Rte_08052][SWS_Rte_08053] */
#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_SYS_KPI_ADAPTER_TYPE_H */

/* End Rte Generator V2 section ***********************************************/


/* End of File Rte_SYS_KPI_ADAPTER_Type.h=====================================*/
