/******************************************************************************
 ** File: Rte_DataHandleType.h
 ** Role: The RTE Data Handle Types Header File contains the Data Handle type declarations necessary for the component data structures
 ** Generated by Dassault Systèmes Rte Generator
 ** Date: 2023-02-09 08:55:42
 ** Template Version: 0.1
 **
 ** Controller / Compiler / Hardware independent
 **
 ** Copyright 2012 by Dassault Systèmes
 ** All rights exclusively reserved for Dassault Systèmes,
 ** unless expressly agreed to otherwise.
 ** Traceability: [rte_sws_7922][rte_sws_7923][rte_sws_7921]
*******************************************************************************/
#ifndef RTE_DATA_HANDLE_TYPE_H
#define RTE_DATA_HANDLE_TYPE_H

/* Rte_DataHandleType.h Traceability [rte_sws_7922] ***************************/

/* Rte Generator V2 section ***************************************************/

/** Traceability [rte_sws_7678]*/
#ifndef RTE_RTE_DATA_HANDLE_TYPE_H
#define RTE_RTE_DATA_HANDLE_TYPE_H


/* Data Element without Status ************************************************/
/* Traceability [rte_sws_7920][rte_sws_1363][rte_sws_1364][rte_sws_2607] ******/


/* Data Element with Status ****************************************************/
/* Traceability [rte_sws_1365][rte_sws_1366][rte_sws_3734][rte_sws_2666][rte_sws_2589][rte_sws_2590] */

#endif /* RTE_DATA_HANDLE_TYPE_H */

/* End Rte Generator V2 section ***********************************************/

#endif /* RTE_DATA_HANDLE_TYPE_H */

/* End of File Rte_DataHandleType.h ==========================================*/

