/******************************************************************************
 ** File: Rte_DMA_ADAPTER_Type.h
 ** Role: The Application Types Header File provides a component local name space for enumeration literals and range values 
 ** Generated by Dassault Systèmes Rte Generator
 ** Date: 2023-02-09 08:57:37
 ** Template Version: 0.1
 **
 ** Controller / Compiler / Hardware independent
 **
 ** Copyright 2012 by Dassault Systèmes
 ** All rights exclusively reserved for Dassault Systèmes,
 ** unless expressly agreed to otherwise.
 ** Traceability: [rte_sws_7121][rte_sws_7122][rte_sws_7123][rte_sws_7124][rte_sws_2627]
*******************************************************************************/

/* Rte_DMA_ADAPTER_Type.h *****************************************************/

/* Rte Generator V2 section ***************************************************/

/** Traceability [rte_sws_7678]*/
#ifndef RTE_DMA_ADAPTER_TYPE_H
#define RTE_DMA_ADAPTER_TYPE_H


/* Inclusions ================================================================*/
#include "Rte_Type.h"         /* RTE types header file Traceability [rte_sws_7127]*/
/** Traceability [rte_sws_7123] The declarations below are included only by the SwC, not by the RTE */

/* Implementation Data Type Symbols Traceability [rte_sws_6718]===============*/


/* Macros for accessing Availability Information in Structs for optional Members [SWS_Rte_3611][SWS_Rte_3612][SWS_Rte_3613][SWS_Rte_3614][SWS_Rte_3615][SWS_Rte_3616][SWS_Rte_3617][SWS_Rte_3618]===============*/


/* RTE Modes Traceability [rte_sws_2659][rte_sws_2627][rte_sws_2568]==========*/


/* Enumeration Data Types Traceability [rte_sws_3809][rte_sws_3810]===========*/
#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */


/* BitField Data Types Traceability [SWS_Rte_07410][SWS_Rte_07411][SWS_Rte_07412]===========*/
#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */


/* Range Data Types Traceability [rte_sws_5052][rte_sws_8402][rte_sws_5051][rte_sws_8403]*/
#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */


/* Activating Rte Event Data Types [SWS_Rte_08052][SWS_Rte_08053] */
#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_DMA_ADAPTER_TYPE_H */

/* End Rte Generator V2 section ***********************************************/


/* End of File Rte_DMA_ADAPTER_Type.h=========================================*/
