/******************************************************************************
 ** File: Rte_QSF_ADAPTER_Type.h
 ** Role: The Application Types Header File provides a component local name space for enumeration literals and range values 
 ** Generated by Dassault Systèmes Rte Generator
 ** Date: 2023-02-09 08:57:37
 ** Template Version: 0.1
 **
 ** Controller / Compiler / Hardware independent
 **
 ** Copyright 2012 by Dassault Systèmes
 ** All rights exclusively reserved for Dassault Systèmes,
 ** unless expressly agreed to otherwise.
 ** Traceability: [rte_sws_7121][rte_sws_7122][rte_sws_7123][rte_sws_7124][rte_sws_2627]
*******************************************************************************/

/* Rte_QSF_ADAPTER_Type.h *****************************************************/

/* Rte Generator V2 section ***************************************************/

/** Traceability [rte_sws_7678]*/
#ifndef RTE_QSF_ADAPTER_TYPE_H
#define RTE_QSF_ADAPTER_TYPE_H


/* Inclusions ================================================================*/
#include "Rte_Type.h"         /* RTE types header file Traceability [rte_sws_7127]*/
/** Traceability [rte_sws_7123] The declarations below are included only by the SwC, not by the RTE */

/* Implementation Data Type Symbols Traceability [rte_sws_6718]===============*/


/* Macros for accessing Availability Information in Structs for optional Members [SWS_Rte_3611][SWS_Rte_3612][SWS_Rte_3613][SWS_Rte_3614][SWS_Rte_3615][SWS_Rte_3616][SWS_Rte_3617][SWS_Rte_3618]===============*/


/* RTE Modes Traceability [rte_sws_2659][rte_sws_2627][rte_sws_2568]==========*/


/* Enumeration Data Types Traceability [rte_sws_3809][rte_sws_3810]===========*/
#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef QSFA_MEMIF_JOB_OK
#define QSFA_MEMIF_JOB_OK 0U
#endif /* QSFA_MEMIF_JOB_OK */

#ifndef QSFA_MEMIF_JOB_FAILED
#define QSFA_MEMIF_JOB_FAILED 1U
#endif /* QSFA_MEMIF_JOB_FAILED */

#ifndef QSFA_MEMIF_JOB_PENDING
#define QSFA_MEMIF_JOB_PENDING 2U
#endif /* QSFA_MEMIF_JOB_PENDING */

#ifndef QSFA_MEMIF_JOB_CANCELED
#define QSFA_MEMIF_JOB_CANCELED 3U
#endif /* QSFA_MEMIF_JOB_CANCELED */

#ifndef QSFA_MEMIF_BLOCK_INCONSISTENT
#define QSFA_MEMIF_BLOCK_INCONSISTENT 4U
#endif /* QSFA_MEMIF_BLOCK_INCONSISTENT */

#ifndef QSFA_MEMIF_BLOCK_INVALID
#define QSFA_MEMIF_BLOCK_INVALID 5U
#endif /* QSFA_MEMIF_BLOCK_INVALID */

#ifndef QSFA_MEMIF_UNINIT
#define QSFA_MEMIF_UNINIT 0U
#endif /* QSFA_MEMIF_UNINIT */

#ifndef QSFA_MEMIF_IDLE
#define QSFA_MEMIF_IDLE 1U
#endif /* QSFA_MEMIF_IDLE */

#ifndef QSFA_MEMIF_BUSY
#define QSFA_MEMIF_BUSY 2U
#endif /* QSFA_MEMIF_BUSY */

#ifndef QSFA_MEMIF_BUSY_INTERNAL
#define QSFA_MEMIF_BUSY_INTERNAL 3U
#endif /* QSFA_MEMIF_BUSY_INTERNAL */

#ifndef QSFA_MEMIF_MODE_SLOW
#define QSFA_MEMIF_MODE_SLOW 0U
#endif /* QSFA_MEMIF_MODE_SLOW */

#ifndef QSFA_MEMIF_MODE_FAST
#define QSFA_MEMIF_MODE_FAST 1U
#endif /* QSFA_MEMIF_MODE_FAST */


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */


/* BitField Data Types Traceability [SWS_Rte_07410][SWS_Rte_07411][SWS_Rte_07412]===========*/
#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */


/* Range Data Types Traceability [rte_sws_5052][rte_sws_8402][rte_sws_5051][rte_sws_8403]*/
#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */


/* Activating Rte Event Data Types [SWS_Rte_08052][SWS_Rte_08053] */
#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_QSF_ADAPTER_TYPE_H */

/* End Rte Generator V2 section ***********************************************/


/* End of File Rte_QSF_ADAPTER_Type.h=========================================*/
